services:
  - type: web
    name: fastapi-backend
    runtime: python
    region: singapore
    plan: free
    rootDir: server
    buildCommand: ""  # No need to build manually for Python
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=10000
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-db
          property: connectionString  

databases:
  - name: fastapi-db
    plan: free
