"""Image-Field

Revision ID: 2f52966c0266
Revises: 2acbfb178f78
Create Date: 2025-03-25 17:10:33.718737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f52966c0266'
down_revision: Union[str, None] = '2acbfb178f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tools_id', table_name='tools')
    op.drop_table('tools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('categories', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pricing', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('problem_it_solves', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_features', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('requires_account', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('blog_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('blog_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tools_pkey')
    )
    op.create_index('ix_tools_id', 'tools', ['id'], unique=False)
    # ### end Alembic commands ###
