"""removed blog_title and post

Revision ID: 55439f7d0edc
Revises: c6b6d86f8a8d
Create Date: 2025-10-09 16:45:21.999719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55439f7d0edc'
down_revision: Union[str, None] = 'c6b6d86f8a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'blog_content')
    op.drop_column('tools', 'blog_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('blog_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tools', sa.Column('blog_content', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
