"""admin tweaks

Revision ID: 573d0a373d78
Revises: 2cd9e20af4c3
Create Date: 2025-03-29 12:24:54.978055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573d0a373d78'
down_revision: Union[str, None] = '2cd9e20af4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tools_id', table_name='tools')
    op.drop_table('tools')
    op.drop_index('ix_admins_id', table_name='admins')
    op.drop_table('admins')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admins_pkey'),
    sa.UniqueConstraint('username', name='admins_username_key')
    )
    op.create_index('ix_admins_id', 'admins', ['id'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('categories', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pricing', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('problem_it_solves', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_features', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('requires_account', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('blog_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('blog_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tools_pkey'),
    sa.UniqueConstraint('url', name='tools_url_key')
    )
    op.create_index('ix_tools_id', 'tools', ['id'], unique=False)
    # ### end Alembic commands ###
