"""Added columns

Revision ID: cf176d1855cb
Revises: 1ca89ae6cad8
Create Date: 2025-03-20 10:42:18.656759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf176d1855cb'
down_revision: Union[str, None] = '1ca89ae6cad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_id', table_name='tool')
    op.drop_index('ix_tool_name', table_name='tool')
    op.drop_table('tool')
    op.drop_index('ix_tools_id', table_name='tools')
    op.drop_index('ix_tools_name', table_name='tools')
    op.drop_table('tools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('categories', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tools_pkey')
    )
    op.create_index('ix_tools_name', 'tools', ['name'], unique=False)
    op.create_index('ix_tools_id', 'tools', ['id'], unique=False)
    op.create_table('tool',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('categories', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tool_pkey')
    )
    op.create_index('ix_tool_name', 'tool', ['name'], unique=False)
    op.create_index('ix_tool_id', 'tool', ['id'], unique=False)
    # ### end Alembic commands ###
