import React from 'react';
import NavBar from './components/NavBar';
import LanHero from './components/LanHero';
import Category from './components/Category';
import Footer from './components/Footer';
import type { Metadata } from 'next';

// #TODO move metadata to all pages during production
export const metadata: Metadata = {
  title: 'DevJuice',
  description: 'Generated by create next app',
};

const page = () => {
  return (
    <div className="bg-black text-white">
      <NavBar />
      <LanHero />
      <Category />
      <Footer />
    </div>
  );
};

export default page;
